version: '2'

services:
  redis:
    image: redis:alpine
    command: --save 900 1
    restart: on-failure:5
    network_mode: "host"
  ntopng:
    build:
      context: ntop
      dockerfile: Dockerfile
    command: ntopng -r localhost:6379 -d /ntopngcustom
    restart: on-failure:5
    network_mode: "host"
    depends_on:
      - redis